# AUTO-GENERATED by scripts/gen_sync.py from proto_client/_async/_ndjson.py.
# Do not edit this file directly — edit the async source and rerun
# `python scripts/gen_sync.py`.
"""Sync NDJSON streaming helpers — AUTO-GENERATED from proto_client/_async/_ndjson.py."""

import logging
from collections.abc import Iterator
from typing import Any

import httpx

from proto_client.errors import from_response
from proto_client.models import LogRecord, LogsPage

logger = logging.getLogger(__name__)


def _iter_ndjson_records(
    http: httpx.Client,
    path: str,
    params: dict[str, Any],
) -> Iterator[LogRecord]:
    """Stream :class:`LogRecord` rows; yields the ``system: __end__`` terminator then stops."""
    logger.debug("GET %s (stream)", path)
    with http.stream("GET", path, params=params) as resp:
        logger.debug("GET %s -> %d", path, resp.status_code)
        if resp.is_error:
            resp.read()
            raise from_response(resp)
        for line in resp.iter_lines():
            if not line:
                continue
            record = LogRecord.model_validate_json(line)
            yield record
            if record.stream == "system" and record.msg == "__end__":
                return


def _collect_logs_page(records_iter: Iterator[LogRecord], since: int | None) -> LogsPage:
    """Drain *records_iter* into a :class:`LogsPage`. Server ``?since`` is exclusive, so resume cursor = ``last.seq``."""
    records: list[LogRecord] = []
    end_seen = False
    for record in records_iter:
        records.append(record)
        if record.stream == "system" and record.msg == "__end__":
            end_seen = True
    if end_seen:
        next_since: int | None = None
    elif records:
        next_since = records[-1].seq
    else:
        next_since = since
    return LogsPage(records=records, next_since=next_since)
