# AUTO-GENERATED by scripts/gen_sync.py from proto_client/_async/_ndjson.py.
# Do not edit this file directly — edit the async source and rerun
# `python scripts/gen_sync.py`.
"""Sync NDJSON streaming helpers — AUTO-GENERATED from proto_client/_async/_ndjson.py."""

import json
import logging
from collections.abc import Iterator
from typing import Any, Literal

import httpx

from proto_client.errors import from_response
from proto_client.models import LogRecord, LogsEnd, LogsPage

logger = logging.getLogger(__name__)


def _iter_ndjson_records(
    http: httpx.Client,
    path: str,
    params: dict[str, Any],
) -> Iterator[LogRecord | LogsEnd]:
    """Stream NDJSON log items, yielding the :class:`LogsEnd` terminator (if any) then stopping."""
    logger.debug("GET %s (stream)", path)
    with http.stream("GET", path, params=params) as resp:
        logger.debug("GET %s -> %d", path, resp.status_code)
        if resp.is_error:
            resp.read()
            raise from_response(resp)
        for line in resp.iter_lines():
            if not line:
                continue
            payload = json.loads(line)
            if payload["type"] == "end":
                yield LogsEnd.model_validate(payload)
                return
            yield LogRecord.model_validate(payload)


def _collect_logs_page(
    items: Iterator[LogRecord | LogsEnd],
    since: int | None,
) -> LogsPage:
    """Drain *items* into a :class:`LogsPage`."""
    records: list[LogRecord] = []
    end_reason: Literal["completed", "truncated", "idle_timeout"] | None = None
    for item in items:
        if isinstance(item, LogsEnd):
            end_reason = item.reason
        else:
            records.append(item)
    if end_reason is not None:
        next_since: int | None = None
    elif records:
        next_since = records[-1].seq
    else:
        next_since = since
    return LogsPage(records=records, next_since=next_since, end_reason=end_reason)
