# AUTO-GENERATED by scripts/gen_sync.py from proto_client/_async/runs.py.
# Do not edit this file directly — edit the async source and rerun
# `python scripts/gen_sync.py`.
"""Sync runs namespace — AUTO-GENERATED from proto_client/_async/runs.py.

Do not edit this file directly. Edit the async source and run
``python scripts/gen_sync.py`` to regenerate.
"""

import logging
import time
from time import sleep as _sleep
from typing import Any

import httpx

from proto_client.errors import RunCancelledError, RunFailedError, from_response
from proto_client.models import (
    ConstraintSpec,
    CreateRunResponse,
    GeneratorSpec,
    OptimizerSpec,
    RunResponse,
    RunStatus,
    StageTimepointHistory,
    ValidationResponse,
)

logger = logging.getLogger("proto_client.runs")

# Terminal run statuses — polling stops when a run reaches any of these.
_TERMINAL_STATUSES = frozenset({RunStatus.completed, RunStatus.failed, RunStatus.cancelled})


class RunsNamespace:
    """Access the runs API runs, validation, timepoints, and registries.

    Usage::

        with ProtoClient(...) as client:
            run = client.runs.create(program_data={...})
            status = client.runs.get(run.run_id)
    """

    def __init__(self, http: httpx.Client) -> None:
        """Initialize with an httpx Client."""
        self._http = http

    # ------------------------------------------------------------------ runs

    def create(
        self,
        program_data: dict[str, Any],
        execute: bool = True,
        webhook_url: str | None = None,
        webhook_metadata: dict[str, Any] | None = None,
    ) -> CreateRunResponse:
        """POST /api/v1/runs — create an optimization run.

        With ``execute=True`` (default) the server begins running stages
        immediately. With ``execute=False`` the run is created idle and stages
        must be kicked off with :meth:`run_stage`.
        """
        body: dict[str, Any] = {"program_data": program_data}
        if webhook_url is not None:
            body["webhook_url"] = webhook_url
        if webhook_metadata is not None:
            body["webhook_metadata"] = webhook_metadata
        logger.debug("POST /api/v1/runs")
        resp = self._http.post("/api/v1/runs", params={"execute": str(execute).lower()}, json=body)
        logger.debug("POST /api/v1/runs -> %d", resp.status_code)
        if resp.is_error:
            raise from_response(resp)
        return CreateRunResponse.model_validate(resp.json())

    def get(self, run_id: str) -> RunResponse:
        """GET /api/v1/runs/{run_id} — fetch run status and stage results."""
        path = f"/api/v1/runs/{run_id}"
        logger.debug("GET %s", path)
        resp = self._http.get(path)
        logger.debug("GET %s -> %d", path, resp.status_code)
        if resp.is_error:
            raise from_response(resp)
        return RunResponse.model_validate(resp.json())

    def cancel(self, run_id: str) -> RunResponse:
        """DELETE /api/v1/runs/{run_id} — cancel a running job.

        Propagates the server's 400 if the run is already in a completed or
        failed terminal state; callers need to know that cancelling a finished
        run is a no-op, not silently swallowed.
        """
        path = f"/api/v1/runs/{run_id}"
        logger.debug("DELETE %s", path)
        resp = self._http.delete(path)
        logger.debug("DELETE %s -> %d", path, resp.status_code)
        if resp.is_error:
            raise from_response(resp)
        return RunResponse.model_validate(resp.json())

    def run_stage(self, run_id: str, stage_index: int) -> RunResponse:
        """POST /api/v1/runs/{run_id}/stages/{stage_index}/start — run a single stage.

        Used for incremental execution (after ``create(..., execute=False)``)
        and for re-running a failed stage — the latter is a common beta-user
        recovery path.
        """
        path = f"/api/v1/runs/{run_id}/stages/{stage_index}/start"
        logger.debug("POST %s", path)
        resp = self._http.post(path)
        logger.debug("POST %s -> %d", path, resp.status_code)
        if resp.is_error:
            raise from_response(resp)
        return RunResponse.model_validate(resp.json())

    # ------------------------------------------------------------ validation

    def validate(
        self,
        program_data: dict[str, Any],
    ) -> ValidationResponse:
        """POST /api/v1/validate — validate a program without creating a run.

        Raises ``ProtoValidationError`` (422) when the program is invalid;
        the response body carries a structured ``{"errors": [...]}`` detail.
        """
        logger.debug("POST /api/v1/validate")
        resp = self._http.post("/api/v1/validate", json={"program_data": program_data})
        logger.debug("POST /api/v1/validate -> %d", resp.status_code)
        if resp.is_error:
            raise from_response(resp)
        return ValidationResponse.model_validate(resp.json())

    # ------------------------------------------------------------- timepoints

    def get_timepoints(
        self,
        run_id: str,
        stage: int | None = None,
        offset: int | None = None,
        limit: int = 10000,
        timepoint: int | None = None,
    ) -> list[StageTimepointHistory]:
        """Get optimization timepoints for a run.

        When ``stage`` is ``None`` hits ``GET /api/v1/runs/{run_id}/timepoints`` and
        returns timepoints from every stage. When ``stage`` is set hits
        ``GET /api/v1/runs/{run_id}/stages/{stage}/timepoints`` which additionally
        supports the ``timepoint`` query filter.

        Pass ``limit=0`` to request no cap (the server treats 0 as unlimited).
        """
        params: dict[str, Any] = {"limit": limit}
        if offset is not None:
            params["offset"] = offset
        if stage is None:
            if timepoint is not None:
                raise ValueError("timepoint filter is only supported when stage is specified")
            url = f"/api/v1/runs/{run_id}/timepoints"
        else:
            if timepoint is not None:
                params["timepoint"] = timepoint
            url = f"/api/v1/runs/{run_id}/stages/{stage}/timepoints"
        logger.debug("GET %s", url)
        resp = self._http.get(url, params=params)
        logger.debug("GET %s -> %d", url, resp.status_code)
        if resp.is_error:
            raise from_response(resp)
        return [StageTimepointHistory.model_validate(item) for item in resp.json()]

    # ------------------------------------------------------------- discovery

    def list_constraints(self) -> list[ConstraintSpec]:
        """GET /api/v1/constraints — list registered constraints with their params."""
        logger.debug("GET /api/v1/constraints")
        resp = self._http.get("/api/v1/constraints")
        logger.debug("GET /api/v1/constraints -> %d", resp.status_code)
        if resp.is_error:
            raise from_response(resp)
        return [ConstraintSpec.model_validate(item) for item in resp.json()]

    def list_generators(self) -> list[GeneratorSpec]:
        """GET /api/v1/generators — list registered generators with their params."""
        logger.debug("GET /api/v1/generators")
        resp = self._http.get("/api/v1/generators")
        logger.debug("GET /api/v1/generators -> %d", resp.status_code)
        if resp.is_error:
            raise from_response(resp)
        return [GeneratorSpec.model_validate(item) for item in resp.json()]

    def list_optimizers(self) -> list[OptimizerSpec]:
        """GET /api/v1/optimizers — list registered optimizers with their params."""
        logger.debug("GET /api/v1/optimizers")
        resp = self._http.get("/api/v1/optimizers")
        logger.debug("GET /api/v1/optimizers -> %d", resp.status_code)
        if resp.is_error:
            raise from_response(resp)
        return [OptimizerSpec.model_validate(item) for item in resp.json()]

    @staticmethod
    def _check_terminal(run_id: str, response: RunResponse) -> RunResponse:
        """Return the response if completed, raise if failed/cancelled."""
        state = response.status
        logger.info("Run %s reached terminal status: %s", run_id, state.value)
        if state == RunStatus.completed:
            return response
        if state == RunStatus.cancelled:
            raise RunCancelledError(run_id)
        if state != RunStatus.failed:
            raise AssertionError(f"Unexpected terminal status: {state!r}")
        raise RunFailedError(run_id, response.error_message)

    # ------------------------------------------------------------ convenience

    def run(
        self,
        program_data: dict[str, Any],
        poll_interval: float = 2.0,
        timeout: float = 3600.0,
        webhook_url: str | None = None,
        webhook_metadata: dict[str, Any] | None = None,
    ) -> RunResponse:
        """Submit a run and poll until it reaches a terminal state.

        Returns the final :class:`RunResponse` on success. Raises
        ``RunFailedError`` if the run fails, ``RunCancelledError`` if
        cancelled, and ``TimeoutError`` if it does not complete within
        ``timeout`` seconds.

        On timeout the server-side run is **not** cancelled — callers can
        poll later with the ``run_id`` or cancel explicitly.
        """
        created = self.create(
            program_data,
            execute=True,
            webhook_url=webhook_url,
            webhook_metadata=webhook_metadata,
        )
        run_id = created.run_id
        # Short-circuit if the server already resolved (e.g. instant validation
        # failure) — avoids a redundant GET.
        if created.status in _TERMINAL_STATUSES:
            full = self.get(run_id)
            if full.status in _TERMINAL_STATUSES:
                return self._check_terminal(run_id, full)
            # create() said terminal but get() disagrees (eventual consistency)
            # — fall through to poll loop.
        deadline = time.monotonic() + timeout
        while True:
            status = self.get(run_id)
            if status.status in _TERMINAL_STATUSES:
                return self._check_terminal(run_id, status)
            logger.debug("Polling run %s (status=%s)", run_id, status.status.value)
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise TimeoutError(f"Run {run_id} did not complete within {timeout}s")
            _sleep(min(poll_interval, remaining))
