# AUTO-GENERATED by scripts/gen_sync.py from proto_client/_async/runs.py.
# Do not edit this file directly — edit the async source and rerun
# `python scripts/gen_sync.py`.
"""Sync runs namespace — AUTO-GENERATED from proto_client/_async/runs.py.

Do not edit this file directly. Edit the async source and run
``python scripts/gen_sync.py`` to regenerate.
"""

from __future__ import annotations

import time
from time import sleep as _sleep
from typing import Any

import httpx

# Terminal run statuses — polling stops when a run reaches any of these.
_TERMINAL_STATUSES = frozenset({"completed", "failed", "cancelled"})


class RunsNamespace:
    """Access the runs API runs, validation, timepoints, and registries.

    Usage::

        with ProtoClient(...) as client:
            run = client.runs.create(program_data={...})
            status = client.runs.get(run["run_id"])

    Return types are currently ``dict[str, Any]``. Issue #2 (typed Pydantic
    models) will replace them wholesale once its ``models.py`` lands — this
    is a mechanical find-and-replace tracked in the integration PR.
    """

    def __init__(self, http: httpx.Client):
        self._http = http

    # ------------------------------------------------------------------ runs

    def create(
        self,
        program_data: dict[str, Any],
        execute: bool = True,
        webhook_url: str | None = None,
        webhook_metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """POST /runs — create an optimization run.

        With ``execute=True`` (default) the server begins running stages
        immediately. With ``execute=False`` the run is created idle and stages
        must be kicked off with :meth:`run_stage`.
        """
        body: dict[str, Any] = {"program_data": program_data}
        if webhook_url is not None:
            body["webhook_url"] = webhook_url
        if webhook_metadata is not None:
            body["webhook_metadata"] = webhook_metadata
        resp = self._http.post(
            "/runs", params={"execute": str(execute).lower()}, json=body
        )
        resp.raise_for_status()
        return resp.json()

    def get(self, run_id: str) -> dict[str, Any]:
        """GET /runs/{run_id} — fetch run status and stage results."""
        resp = self._http.get(f"/runs/{run_id}")
        resp.raise_for_status()
        return resp.json()

    def cancel(self, run_id: str) -> dict[str, Any]:
        """DELETE /runs/{run_id} — cancel a running job.

        Propagates the server's 400 if the run is already in a completed or
        failed terminal state; callers need to know that cancelling a finished
        run is a no-op, not silently swallowed.
        """
        resp = self._http.delete(f"/runs/{run_id}")
        resp.raise_for_status()
        return resp.json()

    def run_stage(self, run_id: str, stage_index: int) -> dict[str, Any]:
        """POST /runs/{run_id}/stages/{stage_index}/start — run a single stage.

        Used for incremental execution (after ``create(..., execute=False)``)
        and for re-running a failed stage — the latter is a common beta-user
        recovery path.
        """
        resp = self._http.post(f"/runs/{run_id}/stages/{stage_index}/start")
        resp.raise_for_status()
        return resp.json()

    # ------------------------------------------------------------ validation

    def validate(
        self,
        program_data: dict[str, Any],
    ) -> dict[str, Any]:
        """POST /validate — validate a program without creating a run.

        Raises ``httpx.HTTPStatusError`` (422) when the program is invalid;
        the response body carries a structured ``{"errors": [...]}`` detail.
        """
        resp = self._http.post("/validate", json={"program_data": program_data})
        resp.raise_for_status()
        return resp.json()

    # ------------------------------------------------------------- timepoints

    def get_timepoints(
        self,
        run_id: str,
        stage: int | None = None,
        offset: int | None = None,
        limit: int = 10000,
        timepoint: int | None = None,
    ) -> list[dict[str, Any]]:
        """Get optimization timepoints for a run.

        When ``stage`` is ``None`` hits ``GET /runs/{run_id}/timepoints`` and
        returns timepoints from every stage. When ``stage`` is set hits
        ``GET /runs/{run_id}/stages/{stage}/timepoints`` which additionally
        supports the ``timepoint`` query filter.

        Pass ``limit=0`` to request no cap (the server treats 0 as unlimited).
        """
        params: dict[str, Any] = {"limit": limit}
        if offset is not None:
            params["offset"] = offset
        if stage is None:
            if timepoint is not None:
                raise ValueError(
                    "timepoint filter is only supported when stage is specified"
                )
            url = f"/runs/{run_id}/timepoints"
        else:
            if timepoint is not None:
                params["timepoint"] = timepoint
            url = f"/runs/{run_id}/stages/{stage}/timepoints"
        resp = self._http.get(url, params=params)
        resp.raise_for_status()
        return resp.json()

    # ------------------------------------------------------------- discovery

    def list_constraints(
        self,
    ) -> list[dict[str, Any]]:
        """GET /constraints — list registered constraints with their params."""
        resp = self._http.get("/constraints")
        resp.raise_for_status()
        return resp.json()

    def list_generators(
        self,
    ) -> list[dict[str, Any]]:
        """GET /generators — list registered generators with their params."""
        resp = self._http.get("/generators")
        resp.raise_for_status()
        return resp.json()

    def list_optimizers(
        self,
    ) -> list[dict[str, Any]]:
        """GET /optimizers — list registered optimizers with their params."""
        resp = self._http.get("/optimizers")
        resp.raise_for_status()
        return resp.json()

    def _check_terminal(self, run_id: str, response: dict[str, Any]) -> dict[str, Any]:
        """Return the response if completed, raise if failed/cancelled."""
        state = response["status"]
        if state == "completed":
            return response
        raise RuntimeError(
            f"Run {run_id} ended with status={state!r}: {response.get('error_message')}"
        )

    # ------------------------------------------------------------ convenience

    def run(
        self,
        program_data: dict[str, Any],
        poll_interval: float = 2.0,
        timeout: float = 3600.0,
        webhook_url: str | None = None,
        webhook_metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Submit a run and poll until it reaches a terminal state.

        Returns the final ``RunResponse`` dict on success. Raises
        ``RuntimeError`` if the run ends in ``failed`` or ``cancelled`` and
        ``TimeoutError`` if it does not reach a terminal state within
        ``timeout`` seconds. The polling cadence is naive sleep — v0 streaming
        via SSE is the job of issue #6.
        """
        created = self.create(
            program_data,
            execute=True,
            webhook_url=webhook_url,
            webhook_metadata=webhook_metadata,
        )
        run_id = created["run_id"]
        # Short-circuit if the server already resolved (e.g. instant validation
        # failure) — avoids a redundant GET.
        if created.get("status") in _TERMINAL_STATUSES:
            return self._check_terminal(run_id, self.get(run_id))
        deadline = time.monotonic() + timeout
        while True:
            status = self.get(run_id)
            if status["status"] in _TERMINAL_STATUSES:
                return self._check_terminal(run_id, status)
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise TimeoutError(f"Run {run_id} did not complete within {timeout}s")
            _sleep(min(poll_interval, remaining))
