#!/usr/bin/env python3
"""Regenerate sync modules from their ``proto_client/_async/`` sources.

We use `unasync <https://github.com/python-trio/unasync>`_ — a token-level
transform — to produce sync mirrors of the async source files. The async
versions are authoritative; sync versions are generated and committed.

Run manually::

    python scripts/gen_sync.py

Or via the ``unasync`` pre-commit hook wired up in ``.pre-commit-config.yaml``.

Only files explicitly listed in ``SYNC_TARGETS`` are transformed — we do
NOT point ``todir`` at the whole ``proto_client/`` package, because that
would clobber hand-written modules (``client.py``, ``tools.py``) that
intentionally diverge from their async counterparts.
"""

from __future__ import annotations

from pathlib import Path

import unasync

ROOT = Path(__file__).resolve().parent.parent
ASYNC_DIR = ROOT / "proto_client" / "_async"
SYNC_DIR = ROOT / "proto_client"

# Files in _async/ to convert. Keep this list narrow — client.py and tools.py
# are hand-written on both sides and must not be generated.
SYNC_TARGETS = ["runs.py"]

# Token-level substitutions on top of unasync's defaults (which already handle
# `async def` → `def`, `await x` → `x`, `__aenter__` → `__enter__`, etc.).
# Keys and values must be whole identifiers — unasync matches NAME tokens.
ADDITIONAL_REPLACEMENTS = {
    "AsyncRunsNamespace": "RunsNamespace",
    "AsyncClient": "Client",  # httpx.AsyncClient → httpx.Client
    "aclose": "close",
    # `import asyncio` → `import time`; `asyncio.sleep` → `time.sleep`.
    "asyncio": "time",
}


def main() -> None:
    rule = unasync.Rule(
        fromdir=f"{ASYNC_DIR.as_posix()}/",
        todir=f"{SYNC_DIR.as_posix()}/",
        additional_replacements=ADDITIONAL_REPLACEMENTS,
    )
    files = [str(ASYNC_DIR / name) for name in SYNC_TARGETS]
    unasync.unasync_files(files, [rule])

    # Post-processing: prepend banner and fix docstrings that are misleading
    # when read in the generated sync file (unasync doesn't touch strings).
    banner = (
        "# AUTO-GENERATED by scripts/gen_sync.py from proto_client/_async/{name}.\n"
        "# Do not edit this file directly — edit the async source and rerun\n"
        "# `python scripts/gen_sync.py`.\n"
    )
    docstring_fixups = {
        # Module-level: replace the "source of truth" docstring
        (
            '"""Async runs namespace — wraps the runs API endpoints.\n'
            "\n"
            "This module is the source of truth. The sync counterpart\n"
            "(``proto_client/runs.py``) is generated from this file via unasync in\n"
            "``scripts/gen_sync.py``. Do not edit the generated sync file by hand.\n"
            '"""'
        ): (
            '"""Sync runs namespace — AUTO-GENERATED from'
            " proto_client/_async/runs.py.\n"
            "\n"
            "Do not edit this file directly. Edit the async source and run\n"
            "``python scripts/gen_sync.py`` to regenerate.\n"
            '"""'
        ),
        # Class-level: replace the async usage example
        "async with AsyncProtoClient(...) as client:": (
            "with ProtoClient(...) as client:"
        ),
        "run = await client.runs.create(program_data={...})": (
            "run = client.runs.create(program_data={...})"
        ),
        "status = await client.runs.get(run[": ("status = client.runs.get(run["),
    }
    for name in SYNC_TARGETS:
        out = SYNC_DIR / name
        content = out.read_text()
        for old, new in docstring_fixups.items():
            if old not in content:
                raise ValueError(
                    f"Docstring fixup not found in {name} "
                    f"(async source changed?): {old[:60]!r}"
                )
            content = content.replace(old, new)
        if not content.startswith("# AUTO-GENERATED"):
            content = banner.format(name=name) + content
        out.write_text(content)
    print(f"Regenerated: {', '.join(SYNC_TARGETS)}")


if __name__ == "__main__":
    main()
