#!/usr/bin/env python3
"""Regenerate sync modules from their ``proto_client/_async/`` sources.

We use `unasync <https://github.com/python-trio/unasync>`_ — a token-level
transform — to produce sync mirrors of the async source files. The async
versions are authoritative; sync versions are generated and committed.

Run manually::

    python scripts/gen_sync.py

CI verifies the generated file stays in sync (``Verify Generated Sync Modules``
job in ``.github/workflows/checks.yml``).

Only files explicitly listed in ``SYNC_TARGETS`` are transformed — we do
NOT point ``todir`` at the whole ``proto_client/`` package, because that
would clobber hand-written modules (``client.py``, ``tools.py``) that
intentionally diverge from their async counterparts.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

import unasync  # type: ignore[import-untyped]

ROOT = Path(__file__).resolve().parent.parent
ASYNC_DIR = ROOT / "proto_client" / "_async"
SYNC_DIR = ROOT / "proto_client"

# Files in _async/ to convert. Keep this list narrow — client.py and tools.py
# are hand-written on both sides and must not be generated.
SYNC_TARGETS = ["runs.py"]

# Token-level substitutions on top of unasync's defaults (which already handle
# `async def` → `def`, `await x` → `x`, `__aenter__` → `__enter__`, etc.).
# Keys and values must be whole identifiers — unasync matches NAME tokens.
ADDITIONAL_REPLACEMENTS = {
    "AsyncRunsNamespace": "RunsNamespace",
    "AsyncRunStream": "RunStream",
    "AsyncClient": "Client",  # httpx.AsyncClient → httpx.Client
    "AsyncGenerator": "Generator",
    "aclose": "close",
    "aconnect_sse": "connect_sse",
    "aiter_sse": "iter_sse",
    "anext": "next",
    # `import asyncio` → `import time`; `asyncio.sleep` → `time.sleep`.
    # CAUTION: This replaces *all* `asyncio` tokens with `time`. Only add
    # asyncio usage that has a `time.*` sync equivalent (currently: sleep).
    "asyncio": "time",
}


def main() -> None:
    """Generate sync modules from their async sources via unasync."""
    rule = unasync.Rule(
        fromdir=f"{ASYNC_DIR.as_posix()}/",
        todir=f"{SYNC_DIR.as_posix()}/",
        additional_replacements=ADDITIONAL_REPLACEMENTS,
    )
    files = [str(ASYNC_DIR / name) for name in SYNC_TARGETS]
    unasync.unasync_files(files, [rule])

    # Post-processing: prepend banner and fix docstrings that are misleading
    # when read in the generated sync file (unasync doesn't touch strings).
    banner = (
        "# AUTO-GENERATED by scripts/gen_sync.py from proto_client/_async/{name}.\n"
        "# Do not edit this file directly — edit the async source and rerun\n"
        "# `python scripts/gen_sync.py`.\n"
    )
    docstring_fixups = {
        # Module-level: replace the "source of truth" docstring
        (
            '"""Async runs namespace — wraps the runs API endpoints.\n'
            "\n"
            "This module is the source of truth. The sync counterpart\n"
            "(``proto_client/runs.py``) is generated from this file via unasync in\n"
            "``scripts/gen_sync.py``. Do not edit the generated sync file by hand.\n"
            '"""'
        ): (
            '"""Sync runs namespace — AUTO-GENERATED from'
            " proto_client/_async/runs.py.\n"
            "\n"
            "Do not edit this file directly. Edit the async source and run\n"
            "``python scripts/gen_sync.py`` to regenerate.\n"
            '"""'
        ),
        # Class-level: replace the async usage example
        "async with AsyncProtoClient(...) as client:": ("with ProtoClient(...) as client:"),
        "run = await client.runs.create(program_data={...})": ("run = client.runs.create(program_data={...})"),
        "status = await client.runs.get(run[": ("status = client.runs.get(run["),
        "Initialize with an httpx AsyncClient.": "Initialize with an httpx Client.",
        # Streaming docstrings
        "async for event in client.runs.stream(run_id):": "for event in client.runs.stream(run_id):",
        "async with await client.runs.run_stream(program_data={...}) as stream:": (
            "with client.runs.run_stream(program_data={...}) as stream:"
        ),
        "async for event in stream:": "for event in stream:",
        "an :class:`AsyncRunStream`": "a :class:`RunStream`",
        "Use as an async context manager and async iterator": "Use as a context manager and iterator",
        "        async with stream:": "        with stream:",
        "both async-iterable and\n        an async context manager": ("both iterable and\n        a context manager"),
    }
    for name in SYNC_TARGETS:
        out = SYNC_DIR / name
        content = out.read_text()
        for old, new in docstring_fixups.items():
            if old not in content:
                raise ValueError(f"Docstring fixup not found in {name} (async source changed?): {old[:60]!r}")
            content = content.replace(old, new)
        # AsyncGenerator[Y, S] has 2 type params; Generator[Y, S, R] needs 3.
        # Append the missing ReturnType=None after unasync's token rename.
        content = re.sub(r"Generator\[(\w+), None\]", r"Generator[\1, None, None]", content)
        # Guard against accidental asyncio → time transforms (e.g. time.gather).
        _ALLOWED_TIME_ATTRS = {"time.monotonic", "time.sleep"}
        for match in re.finditer(r"time\.\w+", content):
            if match.group() not in _ALLOWED_TIME_ATTRS:
                raise ValueError(
                    f"Unexpected 'time.' usage in generated {name}: {match.group()!r}. "
                    f"The asyncio→time token replacement likely mangled an asyncio API. "
                    f"Add a targeted replacement rule instead of relying on the blanket rename."
                )
        if not content.startswith("# AUTO-GENERATED"):
            content = banner.format(name=name) + content
        out.write_text(content)
    # Fix import sorting — unasync preserves source order which may not
    # match isort after token replacements (e.g. asyncio→time).
    generated = [str(SYNC_DIR / name) for name in SYNC_TARGETS]
    subprocess.run(  # noqa: S603 — fixed command, no user input
        ["ruff", "check", "--fix", "--select", "I", *generated],  # noqa: S607 — ruff is a dev tool
        check=False,
        capture_output=True,
    )
    print(f"Regenerated: {', '.join(SYNC_TARGETS)}")  # noqa: T201


if __name__ == "__main__":
    main()
