#!/usr/bin/env python3
"""Regenerate sync modules from their ``proto_client/_async/`` sources.

We use `unasync <https://github.com/python-trio/unasync>`_ — a token-level
transform — to produce sync mirrors of the async source files. The async
versions are authoritative; sync versions are generated and committed.

Run manually::

    python scripts/gen_sync.py

checks.yml verifies the generated files stay in sync with their async sources.

Only files explicitly listed in ``SYNC_TARGETS`` are transformed — we do
NOT point ``todir`` at the whole ``proto_client/`` package, because that
would clobber hand-written modules (``client.py``, ``tools.py``,
``assets.py``) that intentionally diverge from their async counterparts.
"""

import re
import subprocess
import sys
from pathlib import Path

import unasync  # type: ignore[import-untyped]

ROOT = Path(__file__).resolve().parent.parent
ASYNC_DIR = ROOT / "proto_client" / "_async"
SYNC_DIR = ROOT / "proto_client"

# Files in _async/ to convert (keep narrow; the hand-written modules must not be generated).
SYNC_TARGETS = ["_ndjson.py", "runs.py"]

# Token-level substitutions on top of unasync's defaults (which already handle
# `async def` → `def`, `await x` → `x`, `__aenter__` → `__enter__`, etc.).
# Keys and values must be whole identifiers — unasync matches NAME tokens.
ADDITIONAL_REPLACEMENTS = {
    "AsyncRunsNamespace": "RunsNamespace",
    "AsyncClient": "Client",  # httpx.AsyncClient → httpx.Client
    "AsyncIterator": "Iterator",  # collections.abc.AsyncIterator
    "aclose": "close",
    "aread": "read",  # httpx Response.aread → Response.read
    "aiter_lines": "iter_lines",  # httpx streaming line iterator
    "_aiter_ndjson_records": "_iter_ndjson_records",
    "_acollect_logs_page": "_collect_logs_page",
    # `from asyncio import sleep as _sleep` → `from time import sleep as _sleep`.
    # CAUTION: This replaces *all* `asyncio` tokens with `time`. Only add
    # asyncio usage that has a `time.*` sync equivalent (currently: sleep).
    "asyncio": "time",
}

# Per-file docstring/usage-example fixups. unasync only rewrites NAME tokens —
# strings inside docstrings still read "Async ..." after the transform, which
# is misleading in the generated sync file. Every (old, new) pair MUST be
# present in the source; missing fixups raise to flag drift.
DOCSTRING_FIXUPS: dict[str, dict[str, str]] = {
    "runs.py": {
        # Module-level: replace the "source of truth" docstring.
        (
            '"""Async runs namespace — wraps the runs API endpoints.\n'
            "\n"
            "This module is the source of truth. The sync counterpart\n"
            "(``proto_client/runs.py``) is generated from this file via unasync in\n"
            "``scripts/gen_sync.py``. Do not edit the generated sync file by hand.\n"
            '"""'
        ): (
            '"""Sync runs namespace — AUTO-GENERATED from'
            " proto_client/_async/runs.py.\n"
            "\n"
            "Do not edit this file directly. Edit the async source and run\n"
            "``python scripts/gen_sync.py`` to regenerate.\n"
            '"""'
        ),
        # Class-level: replace the async usage example.
        "async with AsyncProtoClient(...) as client:": "with ProtoClient(...) as client:",
        "run = await client.runs.create(program_data={...})": "run = client.runs.create(program_data={...})",
        "status = await client.runs.get(run.run_id)": "status = client.runs.get(run.run_id)",
        "Initialize with an httpx AsyncClient.": "Initialize with an httpx Client.",
    },
    "_ndjson.py": {
        '"""Async NDJSON streaming helpers shared by runs.iter_logs and tools.iter_job_logs."""': (
            '"""Sync NDJSON streaming helpers — AUTO-GENERATED from proto_client/_async/_ndjson.py."""'
        ),
    },
}


def main() -> None:
    """Generate sync modules from their async sources via unasync."""
    rule = unasync.Rule(
        fromdir=f"{ASYNC_DIR.as_posix()}/",
        todir=f"{SYNC_DIR.as_posix()}/",
        additional_replacements=ADDITIONAL_REPLACEMENTS,
    )
    files = [str(ASYNC_DIR / name) for name in SYNC_TARGETS]
    unasync.unasync_files(files, [rule])

    # Prepend the generated-file banner and apply the docstring fixups.
    banner = (
        "# AUTO-GENERATED by scripts/gen_sync.py from proto_client/_async/{name}.\n"
        "# Do not edit this file directly — edit the async source and rerun\n"
        "# `python scripts/gen_sync.py`.\n"
    )
    for name in SYNC_TARGETS:
        out = SYNC_DIR / name
        content = out.read_text()
        for old, new in DOCSTRING_FIXUPS.get(name, {}).items():
            if old not in content:
                raise ValueError(f"Docstring fixup not found in {name} (async source changed?): {old[:60]!r}")
            content = content.replace(old, new)
        # unasync rewrites NAME tokens but not module paths in imports.
        content = content.replace("from proto_client._async.", "from proto_client.")
        # After `async` is collapsed, ruff UP028 wants `yield from` for the trivial forwarding pattern.
        content = re.sub(
            r"(\s+)for (\w+) in ([^:\n]+):\n\s+yield \2\n",
            lambda m: f"{m.group(1)}yield from {m.group(3)}\n",
            content,
        )
        # Guard against accidental asyncio → time transforms (e.g. time.gather).
        _ALLOWED_TIME_ATTRS = {"time.monotonic"}
        for match in re.finditer(r"time\.\w+", content):
            if match.group() not in _ALLOWED_TIME_ATTRS:
                raise ValueError(
                    f"Unexpected 'time.' usage in generated {name}: {match.group()!r}. "
                    f"The asyncio→time token replacement likely mangled an asyncio API. "
                    f"Add a targeted replacement rule instead of relying on the blanket rename."
                )
        if not content.startswith("# AUTO-GENERATED"):
            content = banner.format(name=name) + content
        out.write_text(content)

    # Re-sort imports + format the generated files. The asyncio→time rename
    # reorders `from X import` lines alphabetically, so the unasync output is
    # almost always lint-dirty without this pass.
    paths = [str(SYNC_DIR / name) for name in SYNC_TARGETS]
    # Args are all constants (sys.executable + literals + paths from SYNC_TARGETS).
    subprocess.run([sys.executable, "-m", "ruff", "check", "--fix", "--select", "I", *paths], check=True)  # noqa: S603
    subprocess.run([sys.executable, "-m", "ruff", "format", *paths], check=True)  # noqa: S603

    print(f"Regenerated: {', '.join(SYNC_TARGETS)}")  # noqa: T201


if __name__ == "__main__":
    main()
